### ISSUE TITLE
.index method handles tuple keys as iterables

### ISSUE THREAD

**Issue by leo-labs** [LuminosoInsight/ordered-set#16]
Apparently `.index(key)` handles all iterables (except strings) as list of subkeys. 
When using tuples as keys, this will break. 

Can we either add an extra case for tuples *or* remove the extra logic for iterables?

**Comment by rspeer** [comment]
You make a good point that the behavior on iterables is unexpected.

Taking in a list of keys is important for my use case because it corresponds to NumPy's "fancy indexing", and OrderedSets are great for labeling NumPy matrices. But tuples aren't fancy indices in NumPy anyway, so tuples shouldn't necessarily cause fancy indexing.

However, could you describe what you think should happen instead? The actual indices of an OrderedSet are integers, so what *should* happen when you index an OrderedSet with a tuple? Just an error?

**Comment by leo-labs** [comment]
From what I understand, `.index(key)` should give me the index of an entry in my OrderedSet.
e.g. for the OrderedSet `{(2,4), (3,5), (1,0)}` it should behave like
`.index((2,4)) = 0`
`.index((3,5)) = 1`
`.index((1,0)) = 2`

I proposed a fix with pull request #17

**Comment by rspeer** [comment]
Oh! I was thinking about the opposite direction, with `__getitem__`. This makes sense.

**Comment by rspeer** [comment]
Closed by merging #17.
