### ISSUE TITLE
Support an option to create immutable set

### ISSUE THREAD

**Issue by rominf** [LuminosoInsight/ordered-set#35]
I need to pass ordered set as function default argument, therefore, I need an immutable set. Please provide a way to create an immutable set.

**Comment by rspeer** [comment]
I'm worried about scope creep.

An immutable version of OrderedSet would clearly be useful in a few cases, but maybe it should just be a different package. There's a lot of methods of OrderedSet that it wouldn't need.

**Comment by rominf** [comment]
But that means that lot's of code would be duplicated. Isn't possible to create a base class to implement all common functionality and create two subclasses?

**Comment by rspeer** [comment]
I'm really not interested in writing extra code for this use case. When you need a small immutable sequence that you can use as a default argument, a tuple should do just fine.

**Comment by Eric-Arellano** [comment]
Hello, rather than this being a flag on the original `OrderedSet`, I'd love for there to be a new `FrozenOrderedSet` (like `frozenset` but ordered).

I am happy to put up a PR for this, including comprehensive tests and type hints, given your blessing. (It's okay if you don't want to commit to it at this point - if you'd like to see the PR first before accepting the overall idea, let me know and I'd be happy to do so.) 

Why do I care about this? I'm one of the maintainers of [Pex](https://github.com/pantsbuild/pex) and [Pants](https://github.com/pantsbuild/pants). For the build tool Pants, our caching model depends on stable iteration _and_ immutability. `OrderedSet` provides is this first property, and we're hoping to add `FrozenOrderedSet` to have both properties. We thought about inlining it, but believe `FrozenOrderedSet` would be helpful to others.

(Possible further context: Python is considering PEP 603 to add a builtin `frozenmap`: https://www.python.org/dev/peps/pep-0603/)
